package constants

// Order flow types
const (
	ORDER_FLOW_BUY  = "BUY"
	ORDER_FLOW_SELL = "SELL"
)

// Order type constants
const (
	ORDER_TYPE_LIMIT  = "LIMIT"
	ORDER_TYPE_MARKET = "MARKET"
	ORDER_TYPE_STOP   = "STOP"
)

// Order status constants
const (
	ORDER_STATUS_CREATED               = "CREATED"
	ORDER_STATUS_PENDING               = "PENDING"
	ORDER_STATUS_DEPOSIT_CONFIRMING    = "DEPOSIT_CONFIRMING"
	ORDER_STATUS_DEPOSIT_CONFIRMED     = "DEPOSIT_CONFIRMED"
	ORDER_STATUS_WITHDRAWAL_CONFIRMING = "WITHDRAWAL_CONFIRMING"
	ORDER_STATUS_WITHDRAWAL_CONFIRMED  = "WITHDRAWAL_CONFIRMED"
	ORDER_STATUS_FILLED                = "FILLED"
	ORDER_STATUS_OVERPAID              = "OVERPAID"
	ORDER_STATUS_UNDERPAID             = "UNDERPAID"
	ORDER_STATUS_REFUNDED              = "REFUNDED"
	ORDER_STATUS_FAILED                = "FAILED"
	ORDER_STATUS_EXPIRED               = "EXPIRED"
)

// Order transaction type constants
const (
	ORDER_TRANSACTION_DEPOSIT           = "DEPOSIT"
	ORDER_TRANSACTION_WITHDRAWAL        = "WITHDRAWAL"
	ORDER_TRANSACTION_REFUND            = "REFUND"
	ORDER_TRANSACTION_FEES_GAINED       = "FEES_GAINED"
	ORDER_TRANSACTION_FEES_PAID         = "FEES_PAID"
	ORDER_TRANSACTION_OPERATIONAL_COSTS = "OPERATIONAL_COSTS"
)

// Order class constants
const (
	ORDER_CLASS_APP    = "App"
	ORDER_CLASS_OTC    = "Otc"
	ORDER_CLASS_MANUAL = "Manual"
)

// Platform constants
const (
	PLATFORM_APP = "APP"
	PLATFORM_WEB = "WEB"
	PLATFORM_API = "API"
)
